### ISSUE TITLE
how to build .so file

### ISSUE THREAD

**Issue by hotpeperoncino** [qingkaishi/canary#2]
I'd like to use .so file and use -load option. can I have how to build it ?

**Comment by qingkaishi** [comment]
Currently, the building script does not support. But you can easily do it because you can find all .o files in canary/lib/ directory after building with current script. With those .o files, you can use the command `gcc -shared` to build a shared library (i.e., .so).

**Comment by hotpeperoncino** [comment]
thank you for your reply. -fPIC option is required for each compilation...


2016/12/21 17:03 "Qingkai Shi" <notifications@github.com>:

Currently, the building script does not support. But you can easily do it
because you can find all .o files in canary/lib/ directory after building
with current script. With those .o files, you can use the command gcc
-shared to build a shared library (i.e., .so).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/qingkaishi/canary/issues/2#issuecomment-268460362>, or mute
the thread
